apiVersion: apps/v1
kind: Deployment
metadata:
  name: potathon-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: potathon-backend
  template:
    metadata:
      labels:
        app: potathon-backend
    spec:
      containers:
        - name: potathon-backend
          image: poteto0/potathon-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
