version: "3.8"

services:
  calculator:
    container_name: calculator
    build:
      context: calculator
      dockerfile: Dockerfile
    ports:
      - 2000:2000
    volumes:
      - ./calculator/app:/app

  redis:
    container_name: potathon-kvs
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/potathon-kvs:/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    env_file:
      - backend/app/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend/app:/app
    depends_on:
      - redis

  nginx:
    container_name: proxy
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  kvs:

networks:
  default:
