apiVersion: apps/v1
kind: Deployment
metadata:
  name: potathon-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: potathon-nginx
  template:
    metadata:
      labels:
        app: potathon-nginx
    spec:
      containers:
        - name: potathon-nginx
          image: poteto0/potathon-nginx:latest
          ports:
            - containerPort: 80
