apiVersion: v1
kind: Service
metadata:
  name: potathon-nginx-service
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: potathon-nginx
