name: test

on: [push, workflow_call]

jobs:
  backend_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/app

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: install
        run: go mod tidy

      - name: test coverage
        run: go test ./... -cover -gcflags=all=-l
